### ISSUE TITLE
Production url

### ISSUE THREAD

**Issue by smclelland** [epeli/piler#30]
Getting this with express 3 in production.   Works in development.  Thoughts?

``` html
<link rel="stylesheet" href="/pile/min/undefined/global.css"  />
```

**Comment by dhrumil4u360** [comment]
With Express 4.15.3 none of above worked! You need to change your app listener like this to make it working in production.

```

var clientjs = piler.createJSManager();
var clientcss = piler.createCSSManager();
...
...
app.listen(app.get('port'), function () {
    if (process.env.NODE_ENV === 'production') {
        clientjs.pileUp();
        clientcss.pileUp();
    }
    console.log('app running on port', app.get('port'));
});
```
Any update to repo really appreciated or please suggest better alternative if any.
