### ISSUE TITLE
upcoming 1.0.0

### ISSUE THREAD

**Issue by pocesar** [epeli/piler#54]
Achieve stable code, a lot of breaking API changes to come

**Comment by niallobrien** [comment]
Is this project still alive?

**Comment by pocesar** [comment]
@niallobrien it is actually, but the repo version is outdated

**Comment by brendon1982** [comment]
Hi,

I've looked at a lot of other asset managers and this on is my favorite thus far. I was just wondering what your plans are for the project, because there isn't a npm package for 1.0.0 and you mention above that the repo is out of date. For now I've just added the lib folder into my project and am using it like that.

Thanks

**Comment by pocesar** [comment]
I've created interfaces for extending piler from the outside, so you can plug any type of either cache management, preprocessors, postprocessors, but the API is a bit sloppy because at the time I wasn't using streams, and I should refactor it to do so. Streams are composable, and many other projects use streams, like browserify, which is the main reason piler would work so well with it without the need of a build step

**Comment by xizhao** [comment]
Any updates?

**Comment by pocesar** [comment]
To be honest, I need to know if Piler is still "compatible" with the current node.js and front-end developers flow, which AFAIK it isn't as relevant anymore. 

We have [gulp](https://npmjs.com/package/gulp), [grunt](https://npmjs.com/package/grunt), [browserify](https://npmjs.com/package/browserify), [broccoli](https://npmjs.com/package/broccoli), [bower](https://npmjs.com/package/bower), [component](https://npmjs.com/package/component), [duo](https://npmjs.com/package/duo), that can be used programatically to deal with all types of assets and add a build step, and removing the need for runtime compilation, and offloading the assets cache to specialized third party modules. 

With front end libraries becoming more modular, and isomorphic javascript libraries becoming the norm (use React in both node and the browser, for example), what are the arguments that keeps Piler relevant, I want to make sure it still is so I can keep it alive
