### ISSUE TITLE
New Node.js File Manager

### ISSUE THREAD

**Issue by jdnichollsc** [epeli/piler#67]
Hi man,

Check the new file manager! https://github.com/jdnichollsc/Roxy-Fileman-for-Node.js

Regards, Nicholls

**Comment by esamattis** [comment]
Spam :(

**Comment by jdnichollsc** [comment]
Why? Your project is **Deprecated**, you can recommend the new option in your **README** if you want.

Best regards, Nicholls

**Comment by esamattis** [comment]
Ah. I think you have misuderstood what Piler is (was).  Piler is a server library for sending only JS and CSS files to the browsers which are created by the server developer. Where as Roxy is a GUI for managing files for the enduser of the application.

So getting email for a completely different tool from this repository without explaining why feels just spam even if you didn't meant it to be.

**Comment by jdnichollsc** [comment]
Upps, hahaha excuse me! :+1:
